<?php
$con = mysql_connect('localhost','root');
mysql_select_db('testdata');
echo "hello";
$query1 = "insert into modified select n1.id,n1.headline,n1.startdate,n1.enddate,n1.sourceid,n1.link,datediff(str_to_date(n1.enddate,'%m/%d/%Y %H:%i'),str_to_date(n1.startdate,'%m/%d/%Y %H:%i')),count(distinct n1.sourceid),count(distinct n1.link),timediff(str_to_date(n1.enddate,'%m/%d/%Y %H:%i'),str_to_date(n1.startdate,'%m/%d/%Y %H:%i')) from (select * from news where headline not like '%??????%') n1 group by n1.headline;";
$result1 = mysql_query($query1,$con);

$qq = "insert into ddate select distinct date_format(str_to_date(startdate,'%m/%d/%Y'),'%m/%e/%Y') from modified order by startdate desc;";
$rr = mysql_query($qq,$con); 
$query2 = "insert into article select * from modified where link like '%article%';";
$result2 = mysql_query($query2,$con);
$query3 = "insert into buisness select * from modified where link like '%business%' or headline like '%business%' or link like '%market%' or headline like '%market%';";
$result3 = mysql_query($query3,$con);
$query4 = "insert into city select * from modified where link like '%city%' or headline like '%city%' or headline like '%cities%' or link like '%cities%' or link like '%state%' or headline like '%state%' ;";
$result4 = mysql_query($query4,$con);
$query5 = "insert into companies select * from modified where link like '%company%' or headline like '%company%' or headline like '%companies%' or link like '%companies%';";
$result5 = mysql_query($query5,$con);
$query6 = "insert into economics select * from modified where link like '%economics%' or headline like '%economics%' or link like '%bank%' or headline like '%bank%' or link like '%economy%' or headline like '%economy%' or link like '%commodit%' or headline like '%commodit%';";
$result6 = mysql_query($query6,$con);
$query7 = "insert into extra select * from modified where link like '%content%' or headline like '%content%' or link like '%court%' or headline like '%court%';";
$result7 = mysql_query($query7,$con);
$query8 = "insert into education select * from modified where link like '%education%' or headline like '%education%' or link like '%school%' or headline like '%school%';";
$result8 = mysql_query($query8,$con);

$query9 = "insert into entertainment select * from modified where link like '%music%' or headline like '%music%' or link like '%tv%' or headline like '%tv%' or link like '%television%' or headline like '%television%' or link like '%movie%' or headline like '%movie%' or link like '%bollywood%' or headline like '%bollywood%' or link like '%hollywood%' or headline like '%hollywood%' or (link like '%box%' and link like '%office%') or (headline like '%box%' and headline like '%office%') or link like '%celeb%' or headline like '%celeb%';";
$result9 = mysql_query($query9,$con);

$query10 = "insert into environment select * from modified where link like '%environment%' or headline like '%environment%';";
$result10 = mysql_query($query10,$con);
$query11 = "insert into events select * from modified where link like '%event%' or headline like '%event%';";
$result11 = mysql_query($query11,$con);
$query12 = "insert into health select * from modified where link like '%health%' or headline like '%health%' or link like '%hospital%' or headline like '%hospital%' or link like '%disease%' or headline like '%disease%' or link like '%viral%' or headline like '%viral%' or link like '%ebola%' or headline like '%ebola%';";
$result12 = mysql_query($query12,$con);
$query13 = "insert into india select * from modified where link like '%india%' or headline like '%india%';";
$result13 = mysql_query($query13,$con);
$query14 = "insert into lifestyle select * from modified where (link like '%life%' and link like '%style%') or (headline like '%life%' and headline like '%style%') or link like '%beauty%' or headline like '%beauty%' or link like '%spiritual%' or headline like '%spiritual%' or link like '%yoga%' or headline like '%yoga%';";
$result14 = mysql_query($query14,$con);
$query15 = "insert into multimedia select * from modified where link like '%video%' or headline like '%video%' or link like '%photo%' or headline like '%photo%';";
$result15 = mysql_query($query15,$con);
$query16 = "insert into opinion  select * from modified where link like '%opinion%' or headline like '%opinion%';";
$result16 = mysql_query($query16,$con);
$query17 = "insert into politics select * from modified where link like '%politics%' or headline like '%politics%' or link like '%election%' or headline like '%election%' or link like '%bjp%' or headline like '%bjp%' or link like '%congress%' or headline like '%congress%' or link like '%vote%' or headline like '%vote%';";
$result17 = mysql_query($query17,$con);
$query18 = "insert into science select * from modified where link like '%science%' or headline like '%science%' or link like '%tech%' or headline like '%tech%' or link like '%discover%' or headline like '%discover%' or link like '%gadgets%' or headline like '%gadgets%';";
$result18 = mysql_query($query18,$con);
$query19 = "insert into story select * from modified where link like '%story%' or headline like '%story%';";
$result19 = mysql_query($query19,$con);
$query20 = "insert into sports select * from modified where link like '%sport%' or headline like '%sport%' or link like '%cricket%' or headline like '%cricket%' or link like '%score%' or headline like '%score%' or link like '%play%' or headline like '%play%' or link like '%football%' or headline like '%football%' or link like '%tennis%' or headline like '%tennis%' or link like '%boxer%' or link like '%boxing%' or headline like '%boxer%' or headline like '%boxing%' or link like '%NBA%' or headline like '%NBA%';";
$result20 = mysql_query($query20,$con);
$query21 = "insert into topnews select * from modified where (link like '%top%' and link like '%news%') or (headline like '%top%' and headline like '%news%');";
$result21 = mysql_query($query21,$con);
$query22 = "insert into travel select * from modified where link like '%travel%' or headline like '%travel%' or link like '%tour%' or headline like '%tour%';";
$result22 = mysql_query($query22,$con);
$query23 = "insert into world select * from modified where link like '%world%' or headline like '%world%' or link like '%international%' or headline like '%international%' or link like '%us%' or headline like '%us%';";
$result23 = mysql_query($query23,$con);
$query24 = "insert into blog select * from modified where link like '%blog%' or headline like '%blog%' or link like '%journal%' or headline like '%journal%';";
$result24 = mysql_query($query24,$con);
$query25 = "insert into crime select * from modified where link like '%crime%' or headline like '%crime%' or link like '%violence%' or headline like '%violence%' or link like '%attack%' or headline like '%attack%' or link like '%threat%' or headline like '%threat%';";
$result25 = mysql_query($query25,$con);
$query26 = "insert into articlee select * from article where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result26 = mysql_query($query26,$con);
$query27 = "insert into bloge select * from blog where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result27 = mysql_query($query27,$con);
$query28 = "insert into buisnesse select * from buisness where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result28 = mysql_query($query28,$con);
$query29 = "insert into citye select * from city where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result29 = mysql_query($query29,$con);
$query30 = "insert into companiese select * from companies where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result30 = mysql_query($query30,$con);
$query31 = "insert into crimee select * from crime where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result31 = mysql_query($query31,$con);
$query32 = "insert into economicse select * from economics where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result32 = mysql_query($query32,$con);
$query33 = "insert into entertainmente select * from entertainment where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result33 = mysql_query($query33,$con);
$query34 = "insert into environmente select * from environment where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result34 = mysql_query($query34,$con);
$query35 = "insert into eventse select * from events where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result35 = mysql_query($query35,$con);
$query36 = "insert into educatione select * from education where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result36 = mysql_query($query36,$con);
$query37 = "insert into extrae select * from extra where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result37 = mysql_query($query37,$con);
$query38 = "insert into healthe select * from health where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result38 = mysql_query($query38,$con);
$query39 = "insert into indiae select * from india where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result39 = mysql_query($query39,$con);
$query40 = "insert into lifestylee select * from lifestyle where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result40 = mysql_query($query40,$con);
$query41 = "insert into multimediae select * from multimedia where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result41 = mysql_query($query41,$con);
$query42 = "insert into opinione select * from opinion where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result42 = mysql_query($query42,$con);
$query43 = "insert into politicse select * from politics where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result43 = mysql_query($query43,$con);
$query44 = "insert into sciencee select * from science where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result44 = mysql_query($query44,$con);
$query45 = "insert into sportse select * from sports where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result45 = mysql_query($query45,$con);
$query46 = "insert into storye select * from story where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result46 = mysql_query($query46,$con);
$query47 = "insert into topnewse select * from topnews where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result47 = mysql_query($query47,$con);
$query48 = "insert into travele select * from travel where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result48 = mysql_query($query48,$con);
$query49 = "insert into worlde select * from world where datediff = 0 and clink = 1 and csourceid = 1 and timediff like '00:00:00';";
$result49 = mysql_query($query49,$con);
$query50 = "insert into articlep select * from article where datediff>(select avg(datediff) from article) and clink >1 and csourceid >1;";
$result50 = mysql_query($query50,$con);
$query51 = "insert into blogp select * from blog where datediff >(select avg(datediff) from blog) and clink >1 and csourceid >1;";
$result51 = mysql_query($query51,$con);
$query52 = "insert into buisnessp select * from buisness where datediff >(select avg(datediff) from buisness) and clink >1 and csourceid >1;";
$result52 = mysql_query($query52,$con);
$query53 = "insert into cityp select * from city where datediff >(select avg(datediff) from city) and clink >1 and csourceid >1;";
$result53 = mysql_query($query53,$con);
$query54 = "insert into companiesp select * from companies where datediff >(select avg(datediff) from companies) and clink >1 and csourceid >1;";
$result54 = mysql_query($query54,$con);
$query55 = "insert into crimep select * from crime where datediff >(select avg(datediff) from crime) and clink >1 and csourceid >1;";
$result55 = mysql_query($query55,$con);
$query56 = "insert into economicsp select * from economics where datediff >(select avg(datediff) from economics) and clink >1 and csourceid >1;";
$result56 = mysql_query($query56,$con);
$query57 = "insert into entertainmentp select * from entertainment where datediff >(select avg(datediff) from entertainment) and clink >1 and csourceid >1;";
$result57 = mysql_query($query57,$con);
$query58 = "insert into environmentp select * from environment where datediff >(select avg(datediff) from environment) and clink >1 and csourceid >1;";
$result58 = mysql_query($query58,$con);
$query59 = "insert into eventsp select * from events where datediff >(select avg(datediff) from events) and clink >1 and csourceid >1;";
$result59 = mysql_query($query59,$con);
$query60 = "insert into educationp select * from education where datediff >(select avg(datediff) from education) and clink >1 and csourceid >1;";
$result60 = mysql_query($query60,$con);
$query61 = "insert into extrap select * from extra where datediff >(select avg(datediff) from extra) and clink >1 and csourceid >1;";
$result61 = mysql_query($query61,$con);
$query62 = "insert into healthp select * from health where datediff >(select avg(datediff) from health) and clink >1 and csourceid >1;";
$result62 = mysql_query($query62,$con);
$query63 = "insert into indiap select * from india where datediff >(select avg(datediff) from india) and clink >1 and csourceid >1;";
$result63 = mysql_query($query63,$con);
$query64 = "insert into lifestylep select * from lifestyle where datediff >(select avg(datediff) from lifestyle) and clink >1 and csourceid >1;";
$result64 = mysql_query($query64,$con);
$query65 = "insert into multimediap select * from multimedia where datediff >(select avg(datediff) from multimedia) and clink >1 and csourceid >1;";
$result65 = mysql_query($query65,$con);
$query66 = "insert into opinionp select * from opinion where datediff >(select avg(datediff) from opinion) and clink >1 and csourceid >1;";
$result66 = mysql_query($query66,$con);
$query67 = "insert into politicsp select * from politics where datediff >(select avg(datediff) from politics) and clink >1 and csourceid >1;";
$result67 = mysql_query($query67,$con);
$query68 = "insert into sciencep select * from science where datediff >(select avg(datediff) from science) and clink >1 and csourceid >1;";
$result68 = mysql_query($query68,$con);
$query69 = "insert into sportsp select * from sports where datediff >(select avg(datediff) from sports) and clink >1 and csourceid >1;";
$result69 = mysql_query($query69,$con);
$query70 = "insert into storyp select * from story where datediff >(select avg(datediff) from story) and clink >1 and csourceid >1;";
$result70 = mysql_query($query70,$con);
$query71 = "insert into topnewsp select * from topnews where datediff >(select avg(datediff) from topnews) and clink >1 and csourceid >1;";
$result71 = mysql_query($query71,$con);
$query72 = "insert into travelp select * from travel where datediff >(select avg(datediff) from travel) and clink >1 and csourceid >1;";
$result72 = mysql_query($query72,$con);
$query73 = "insert into worldp select * from world where datediff >(select avg(datediff) from world) and clink >1 and csourceid >1;";
$result73 = mysql_query($query73,$con);
$query74 = "insert into articlet select * from article where csourceid>(select avg(csourceid) from article) and clink>(select avg(clink) from article) ;";
$result74 = mysql_query($query74,$con);
$query75 = "insert into blogt select * from blog where csourceid>(select avg(csourceid) from blog) and clink>(select avg(clink) from blog);";
$result75 = mysql_query($query75,$con);
$query76 = "insert into buisnesst select * from buisness where csourceid>(select avg(csourceid) from buisness) and clink>(select avg(clink) from buisness);";
$result76 = mysql_query($query76,$con);
$query77 = "insert into cityt select * from city where csourceid>(select avg(csourceid) from city) and clink>(select avg(clink) from city);";
$result77 = mysql_query($query77,$con);
$query78 = "insert into companiest select * from companies where csourceid>(select avg(csourceid) from companies) and clink>(select avg(clink) from companies);";
$result78 = mysql_query($query78,$con);
$query79 = "insert into crimet select * from crime where csourceid>(select avg(csourceid) from crime) and clink>(select avg(clink) from crime);";
$result79 = mysql_query($query79,$con);
$query80 = "insert into economicst select * from economics where csourceid>(select avg(csourceid) from economics) and clink>(select avg(clink) from economics);";
$result80 = mysql_query($query80,$con);
$query81 = "insert into entertainmentt select * from entertainment where csourceid>(select avg(csourceid) from entertainment) and clink>(select avg(clink) from entertainment);";
$result81 = mysql_query($query81,$con);
$query82 = "insert into environmentt select * from environment where csourceid>(select avg(csourceid) from environment) and clink>(select avg(clink) from environment);";
$result82 = mysql_query($query82,$con);
$query83 = "insert into eventst select * from events where csourceid>(select avg(csourceid) from events) and clink>(select avg(clink) from events);";
$result83 = mysql_query($query83,$con);
$query84 = "insert into educationt select * from education where csourceid>(select avg(csourceid) from education) and clink>(select avg(clink) from education);";
$result84 = mysql_query($query84,$con);
$query85 = "insert into extrat select * from extra where csourceid>(select avg(csourceid) from extra) and clink>(select avg(clink) from extra);";
$result85 = mysql_query($query85,$con);
$query86 = "insert into healtht select * from health where csourceid>(select avg(csourceid) from health) and clink>(select avg(clink) from health);";
$result86 = mysql_query($query86,$con);
$query87 = "insert into indiat select * from india where csourceid>(select avg(csourceid) from india) and clink>(select avg(clink) from india);";
$result87 = mysql_query($query87,$con);
$query88 = "insert into lifestylet select * from lifestyle where csourceid>(select avg(csourceid) from lifestyle) and clink>(select avg(clink) from lifestyle);";
$result88 = mysql_query($query88,$con);
$query89 = "insert into multimediat select * from multimedia where csourceid>(select avg(csourceid) from multimedia) and clink>(select avg(clink) from multimedia);";
$result89 = mysql_query($query89,$con);
$query90 = "insert into opiniont select * from opinion where csourceid>(select avg(csourceid) from opinion) and clink>(select avg(clink) from opinion);";
$result90 = mysql_query($query90,$con);
$query91 = "insert into politicst select * from politics where csourceid>(select avg(csourceid) from politics) and clink>(select avg(clink) from politics);";
$result91 = mysql_query($query91,$con);
$query92 = "insert into sciencet select * from science where csourceid>(select avg(csourceid) from science) and clink>(select avg(clink) from science);";
$result92 = mysql_query($query92,$con);
$query93 = "insert into sportst select * from sports where csourceid>(select avg(csourceid) from sports) and clink>(select avg(clink) from sports);";
$result93 = mysql_query($query93,$con);
$query94 = "insert into storyt select * from story where csourceid>(select avg(csourceid) from story) and clink>(select avg(clink) from story);";
$result94 = mysql_query($query94,$con);
$query95 = "insert into topnewst select * from topnews where csourceid>(select avg(csourceid) from topnews) and clink>(select avg(clink) from topnews);";
$result95 = mysql_query($query95,$con);
$query96 = "insert into travelt select * from travel where csourceid>(select avg(csourceid) from travel) and clink>(select avg(clink) from travel);";
$result96 = mysql_query($query96,$con);
$query97 = "insert into worldt select * from world where csourceid>(select avg(csourceid) from world) and clink>(select avg(clink) from world);";
$result97 = mysql_query($query97,$con);
echo "hi";

?>